### PR TITLE
862 startup configuration

### PR DESCRIPTION
**Pull request by anthonyboffee**
@rndthoughts This is the startup config stuff plus the typo correction.

See below for example of how to wire up the UpdateEdge wrapper
```
services.AddTransient<IUpdatedgeConfiguration>(s =>
{
     var config = new UpdatedgeConfiguration()
     {
          BaseUrl = "https://uk-test-ueexternalapi.azurewebsites.net",
          ApiKey = "##############################"
     };
     return config;
});
services.AddUpdatedgeApi();
```

We would obviously want to encourage people not to put the Apikey in the code but you get the gist.

Also this may only work with .net Core. For Framework implementations the services may have to be registered via other means - probably through whatever DI package they are using. I think it is possible to use the ServiceCollection but it looks fiddly.

### CODE REVIEW

**Comment by rndthoughts** [comment]
Yes i think .net Framework has no built in DI container.  I'm guessing we could give an example in a different DI container (Ninject, Castle or Simple Injector for example)?

**Comment by rndthoughts** [comment]
I would also use the live url (https://api.updatedge.com) - the internal one is only for our testing purposes.

**Comment by anthonyboffee** [comment]
Yes I'll make sure the example has the live URL, good point.

**Review by rndthoughts — APPROVED** [review]
Other than that, looks good.  There's a few points to discuss shortly about packaging and implementation obviously.

**Pull request merged**
